# ======================== Elasticsearch Configuration =========================
#

cluster.name: {{ .Env.PROVIDER_ELASTICSEARCH_CLUSTER_NAME }}

transport:
    host: {{ .Env.PROVIDER_ELASTICSEARCH_ADDR_TRANSPORT }}
    tcp.port: {{ .Env.PROVIDER_ELASTICSEARCH_PORT_TRANSPORT }}
    tcp.connect_timeout: 2s

discovery.zen:
{{ if .Env.PROVIDER_ELASTICSEARCH_DNSNAMES }}
    hosts_provider: file
{{ end }}
    minimum_master_nodes: 1
    ping_timeout: 3s
    join_timeout: 6s
    fd:
        ping_timeout: 3s
        ping_interval: 1s
        ping_retries: 3

{{ if .Env.PROVIDER_ELASTICSEARCH_DNSNAMES }}
node:
    data: false
    master: false
{{ end }}

path:
    data: /data/local/esdata
    repo: /data/local/essnapshot/snapshots
    logs: /data/local/logs

http:
    enabled: {{ .Env.PROVIDER_ELASTICSEARCH_ENABLE_HTTP }}
    cors.enabled: false
    port: {{ .Env.PROVIDER_ELASTICSEARCH_PORT_HTTP }}
    host: {{ .Env.PROVIDER_ELASTICSEARCH_ADDR_HTTP }}

indices.query.bool.max_clause_count: 10240
search.default_search_timeout: 30s
search.low_level_cancellation: true
